export const Actions = {
  GET_MENU_ITEMS: "GET_MENU_ITEMS",
  ADD_MENU_ITEM: "ADD_MENU_ITEM",
  UPDATE_MENU_ITEM: "UPDATE_MENU_ITEM",
  DELETE_MENU_ITEM: "DELETE_MENU_ITEM",
  RESET_STATE: "RESET_STATE",
};
